local A, L = ...

L.C = {
  fontFamily    = STANDARD_TEXT_FONT,
  fontType      = "ChatFontNormal",
  iconSize      = 42,
  sort          = false, -- Blizz sort is quite shitty
  backdrop = {
    bgFile               = "Interface\\Buttons\\WHITE8x8",
    bgColor              = {0.08, 0.08, 0.1, 0.92},
    edgeFile             = "Interface\\Tooltips\\UI-Tooltip-Border",
    borderColor          = {0.1, 0.1, 0.1, 0.6},
    itemBorderColorAlpha = 0.9,
    tile                 = false,
    tileEdge             = false,
    tileSize             = 16,
    edgeSize             = 16,
    insets               = {left = 3, right = 3, top = 3, bottom = 3}
  },
  bag = {
    padding      = 4,
    maxColumns   = 12,
    minColumns   = 4,
    point        = {"BOTTOM", 800, 200},
    extraHeight  = 16,
  },
  bank = {
    enabled      = true,
    padding      = 4,
    maxColumns   = 24,
    minColumns   = 4,
    point        = {"TOP", -800, -200},
    anchorSlots  = "LEFT", -- "LEFT" or "RIGHT"
    showAllSlots = true, -- whether to show non-bought bank slots
  },
  reagent = {
    enabled      = false,
    containerIds = {-3},
    padding      = 4,
    maxColumns   = 16,
    minColumns   = 4,
    point        = {"TOP", -800, -200},
  },
  items = { -- 20 slots on backpack and 40 for each bag, should be plenty.
    {
      ContainerFrame1Item20,
      ContainerFrame1Item19,
      ContainerFrame1Item18,
      ContainerFrame1Item17,
      ContainerFrame1Item16,
      ContainerFrame1Item15,
      ContainerFrame1Item14,
      ContainerFrame1Item13,
      ContainerFrame1Item12,
      ContainerFrame1Item11,
      ContainerFrame1Item10,
      ContainerFrame1Item9,
      ContainerFrame1Item8,
      ContainerFrame1Item7,
      ContainerFrame1Item6,
      ContainerFrame1Item5,
      ContainerFrame1Item4,
      ContainerFrame1Item3,
      ContainerFrame1Item2,
      ContainerFrame1Item1,
    }, {
      ContainerFrame2Item40,
      ContainerFrame2Item39,
      ContainerFrame2Item38,
      ContainerFrame2Item37,
      ContainerFrame2Item36,
      ContainerFrame2Item35,
      ContainerFrame2Item34,
      ContainerFrame2Item33,
      ContainerFrame2Item32,
      ContainerFrame2Item31,
      ContainerFrame2Item30,
      ContainerFrame2Item29,
      ContainerFrame2Item28,
      ContainerFrame2Item27,
      ContainerFrame2Item26,
      ContainerFrame2Item25,
      ContainerFrame2Item24,
      ContainerFrame2Item23,
      ContainerFrame2Item22,
      ContainerFrame2Item21,
      ContainerFrame2Item20,
      ContainerFrame2Item19,
      ContainerFrame2Item18,
      ContainerFrame2Item17,
      ContainerFrame2Item16,
      ContainerFrame2Item15,
      ContainerFrame2Item14,
      ContainerFrame2Item13,
      ContainerFrame2Item12,
      ContainerFrame2Item11,
      ContainerFrame2Item10,
      ContainerFrame2Item9,
      ContainerFrame2Item8,
      ContainerFrame2Item7,
      ContainerFrame2Item6,
      ContainerFrame2Item5,
      ContainerFrame2Item4,
      ContainerFrame2Item3,
      ContainerFrame2Item2,
      ContainerFrame2Item1,
    }, {
      ContainerFrame3Item40,
      ContainerFrame3Item39,
      ContainerFrame3Item38,
      ContainerFrame3Item37,
      ContainerFrame3Item36,
      ContainerFrame3Item35,
      ContainerFrame3Item34,
      ContainerFrame3Item33,
      ContainerFrame3Item32,
      ContainerFrame3Item31,
      ContainerFrame3Item30,
      ContainerFrame3Item29,
      ContainerFrame3Item28,
      ContainerFrame3Item27,
      ContainerFrame3Item26,
      ContainerFrame3Item25,
      ContainerFrame3Item24,
      ContainerFrame3Item23,
      ContainerFrame3Item22,
      ContainerFrame3Item21,
      ContainerFrame3Item20,
      ContainerFrame3Item19,
      ContainerFrame3Item18,
      ContainerFrame3Item17,
      ContainerFrame3Item16,
      ContainerFrame3Item15,
      ContainerFrame3Item14,
      ContainerFrame3Item13,
      ContainerFrame3Item12,
      ContainerFrame3Item11,
      ContainerFrame3Item10,
      ContainerFrame3Item9,
      ContainerFrame3Item8,
      ContainerFrame3Item7,
      ContainerFrame3Item6,
      ContainerFrame3Item5,
      ContainerFrame3Item4,
      ContainerFrame3Item3,
      ContainerFrame3Item2,
      ContainerFrame3Item1,
    }, {
      ContainerFrame4Item40,
      ContainerFrame4Item39,
      ContainerFrame4Item38,
      ContainerFrame4Item37,
      ContainerFrame4Item36,
      ContainerFrame4Item35,
      ContainerFrame4Item34,
      ContainerFrame4Item33,
      ContainerFrame4Item32,
      ContainerFrame4Item31,
      ContainerFrame4Item30,
      ContainerFrame4Item29,
      ContainerFrame4Item28,
      ContainerFrame4Item27,
      ContainerFrame4Item26,
      ContainerFrame4Item25,
      ContainerFrame4Item24,
      ContainerFrame4Item23,
      ContainerFrame4Item22,
      ContainerFrame4Item21,
      ContainerFrame4Item20,
      ContainerFrame4Item19,
      ContainerFrame4Item18,
      ContainerFrame4Item17,
      ContainerFrame4Item16,
      ContainerFrame4Item15,
      ContainerFrame4Item14,
      ContainerFrame4Item13,
      ContainerFrame4Item12,
      ContainerFrame4Item11,
      ContainerFrame4Item10,
      ContainerFrame4Item9,
      ContainerFrame4Item8,
      ContainerFrame4Item7,
      ContainerFrame4Item6,
      ContainerFrame4Item5,
      ContainerFrame4Item4,
      ContainerFrame4Item3,
      ContainerFrame4Item2,
      ContainerFrame4Item1,
    }, {
      ContainerFrame5Item40,
      ContainerFrame5Item39,
      ContainerFrame5Item38,
      ContainerFrame5Item37,
      ContainerFrame5Item36,
      ContainerFrame5Item35,
      ContainerFrame5Item34,
      ContainerFrame5Item33,
      ContainerFrame5Item32,
      ContainerFrame5Item31,
      ContainerFrame5Item30,
      ContainerFrame5Item29,
      ContainerFrame5Item28,
      ContainerFrame5Item27,
      ContainerFrame5Item26,
      ContainerFrame5Item25,
      ContainerFrame5Item24,
      ContainerFrame5Item23,
      ContainerFrame5Item22,
      ContainerFrame5Item21,
      ContainerFrame5Item20,
      ContainerFrame5Item19,
      ContainerFrame5Item18,
      ContainerFrame5Item17,
      ContainerFrame5Item16,
      ContainerFrame5Item15,
      ContainerFrame5Item14,
      ContainerFrame5Item13,
      ContainerFrame5Item12,
      ContainerFrame5Item11,
      ContainerFrame5Item10,
      ContainerFrame5Item9,
      ContainerFrame5Item8,
      ContainerFrame5Item7,
      ContainerFrame5Item6,
      ContainerFrame5Item5,
      ContainerFrame5Item4,
      ContainerFrame5Item3,
      ContainerFrame5Item2,
      ContainerFrame5Item1,
    }
  },
  borders = { -- The slot borders for all the previous slots
    ContainerFrame1Item20NormalTexture,
    ContainerFrame1Item19NormalTexture,
    ContainerFrame1Item18NormalTexture,
    ContainerFrame1Item17NormalTexture,
    ContainerFrame1Item16NormalTexture,
    ContainerFrame1Item15NormalTexture,
    ContainerFrame1Item14NormalTexture,
    ContainerFrame1Item13NormalTexture,
    ContainerFrame1Item12NormalTexture,
    ContainerFrame1Item11NormalTexture,
    ContainerFrame1Item10NormalTexture,
    ContainerFrame1Item9NormalTexture,
    ContainerFrame1Item8NormalTexture,
    ContainerFrame1Item7NormalTexture,
    ContainerFrame1Item6NormalTexture,
    ContainerFrame1Item5NormalTexture,
    ContainerFrame1Item4NormalTexture,
    ContainerFrame1Item3NormalTexture,
    ContainerFrame1Item2NormalTexture,
    ContainerFrame1Item1NormalTexture,
    ContainerFrame2Item40NormalTexture,
    ContainerFrame2Item39NormalTexture,
    ContainerFrame2Item38NormalTexture,
    ContainerFrame2Item37NormalTexture,
    ContainerFrame2Item36NormalTexture,
    ContainerFrame2Item35NormalTexture,
    ContainerFrame2Item34NormalTexture,
    ContainerFrame2Item33NormalTexture,
    ContainerFrame2Item32NormalTexture,
    ContainerFrame2Item31NormalTexture,
    ContainerFrame2Item30NormalTexture,
    ContainerFrame2Item29NormalTexture,
    ContainerFrame2Item28NormalTexture,
    ContainerFrame2Item27NormalTexture,
    ContainerFrame2Item26NormalTexture,
    ContainerFrame2Item25NormalTexture,
    ContainerFrame2Item24NormalTexture,
    ContainerFrame2Item23NormalTexture,
    ContainerFrame2Item22NormalTexture,
    ContainerFrame2Item21NormalTexture,
    ContainerFrame2Item20NormalTexture,
    ContainerFrame2Item19NormalTexture,
    ContainerFrame2Item18NormalTexture,
    ContainerFrame2Item17NormalTexture,
    ContainerFrame2Item16NormalTexture,
    ContainerFrame2Item15NormalTexture,
    ContainerFrame2Item14NormalTexture,
    ContainerFrame2Item13NormalTexture,
    ContainerFrame2Item12NormalTexture,
    ContainerFrame2Item11NormalTexture,
    ContainerFrame2Item10NormalTexture,
    ContainerFrame2Item9NormalTexture,
    ContainerFrame2Item8NormalTexture,
    ContainerFrame2Item7NormalTexture,
    ContainerFrame2Item6NormalTexture,
    ContainerFrame2Item5NormalTexture,
    ContainerFrame2Item4NormalTexture,
    ContainerFrame2Item3NormalTexture,
    ContainerFrame2Item2NormalTexture,
    ContainerFrame2Item1NormalTexture,
    ContainerFrame3Item40NormalTexture,
    ContainerFrame3Item39NormalTexture,
    ContainerFrame3Item38NormalTexture,
    ContainerFrame3Item37NormalTexture,
    ContainerFrame3Item36NormalTexture,
    ContainerFrame3Item35NormalTexture,
    ContainerFrame3Item34NormalTexture,
    ContainerFrame3Item33NormalTexture,
    ContainerFrame3Item32NormalTexture,
    ContainerFrame3Item31NormalTexture,
    ContainerFrame3Item30NormalTexture,
    ContainerFrame3Item29NormalTexture,
    ContainerFrame3Item28NormalTexture,
    ContainerFrame3Item27NormalTexture,
    ContainerFrame3Item26NormalTexture,
    ContainerFrame3Item25NormalTexture,
    ContainerFrame3Item24NormalTexture,
    ContainerFrame3Item23NormalTexture,
    ContainerFrame3Item22NormalTexture,
    ContainerFrame3Item21NormalTexture,
    ContainerFrame3Item20NormalTexture,
    ContainerFrame3Item19NormalTexture,
    ContainerFrame3Item18NormalTexture,
    ContainerFrame3Item17NormalTexture,
    ContainerFrame3Item16NormalTexture,
    ContainerFrame3Item15NormalTexture,
    ContainerFrame3Item14NormalTexture,
    ContainerFrame3Item13NormalTexture,
    ContainerFrame3Item12NormalTexture,
    ContainerFrame3Item11NormalTexture,
    ContainerFrame3Item10NormalTexture,
    ContainerFrame3Item9NormalTexture,
    ContainerFrame3Item8NormalTexture,
    ContainerFrame3Item7NormalTexture,
    ContainerFrame3Item6NormalTexture,
    ContainerFrame3Item5NormalTexture,
    ContainerFrame3Item4NormalTexture,
    ContainerFrame3Item3NormalTexture,
    ContainerFrame3Item2NormalTexture,
    ContainerFrame3Item1NormalTexture,
    ContainerFrame4Item40NormalTexture,
    ContainerFrame4Item39NormalTexture,
    ContainerFrame4Item38NormalTexture,
    ContainerFrame4Item37NormalTexture,
    ContainerFrame4Item36NormalTexture,
    ContainerFrame4Item35NormalTexture,
    ContainerFrame4Item34NormalTexture,
    ContainerFrame4Item33NormalTexture,
    ContainerFrame4Item32NormalTexture,
    ContainerFrame4Item31NormalTexture,
    ContainerFrame4Item30NormalTexture,
    ContainerFrame4Item29NormalTexture,
    ContainerFrame4Item28NormalTexture,
    ContainerFrame4Item27NormalTexture,
    ContainerFrame4Item26NormalTexture,
    ContainerFrame4Item25NormalTexture,
    ContainerFrame4Item24NormalTexture,
    ContainerFrame4Item23NormalTexture,
    ContainerFrame4Item22NormalTexture,
    ContainerFrame4Item21NormalTexture,
    ContainerFrame4Item20NormalTexture,
    ContainerFrame4Item19NormalTexture,
    ContainerFrame4Item18NormalTexture,
    ContainerFrame4Item17NormalTexture,
    ContainerFrame4Item16NormalTexture,
    ContainerFrame4Item15NormalTexture,
    ContainerFrame4Item14NormalTexture,
    ContainerFrame4Item13NormalTexture,
    ContainerFrame4Item12NormalTexture,
    ContainerFrame4Item11NormalTexture,
    ContainerFrame4Item10NormalTexture,
    ContainerFrame4Item9NormalTexture,
    ContainerFrame4Item8NormalTexture,
    ContainerFrame4Item7NormalTexture,
    ContainerFrame4Item6NormalTexture,
    ContainerFrame4Item5NormalTexture,
    ContainerFrame4Item4NormalTexture,
    ContainerFrame4Item3NormalTexture,
    ContainerFrame4Item2NormalTexture,
    ContainerFrame4Item1NormalTexture,
    ContainerFrame5Item40NormalTexture,
    ContainerFrame5Item39NormalTexture,
    ContainerFrame5Item38NormalTexture,
    ContainerFrame5Item37NormalTexture,
    ContainerFrame5Item36NormalTexture,
    ContainerFrame5Item35NormalTexture,
    ContainerFrame5Item34NormalTexture,
    ContainerFrame5Item33NormalTexture,
    ContainerFrame5Item32NormalTexture,
    ContainerFrame5Item31NormalTexture,
    ContainerFrame5Item30NormalTexture,
    ContainerFrame5Item29NormalTexture,
    ContainerFrame5Item28NormalTexture,
    ContainerFrame5Item27NormalTexture,
    ContainerFrame5Item26NormalTexture,
    ContainerFrame5Item25NormalTexture,
    ContainerFrame5Item24NormalTexture,
    ContainerFrame5Item23NormalTexture,
    ContainerFrame5Item22NormalTexture,
    ContainerFrame5Item21NormalTexture,
    ContainerFrame5Item20NormalTexture,
    ContainerFrame5Item19NormalTexture,
    ContainerFrame5Item18NormalTexture,
    ContainerFrame5Item17NormalTexture,
    ContainerFrame5Item16NormalTexture,
    ContainerFrame5Item15NormalTexture,
    ContainerFrame5Item14NormalTexture,
    ContainerFrame5Item13NormalTexture,
    ContainerFrame5Item12NormalTexture,
    ContainerFrame5Item11NormalTexture,
    ContainerFrame5Item10NormalTexture,
    ContainerFrame5Item9NormalTexture,
    ContainerFrame5Item8NormalTexture,
    ContainerFrame5Item7NormalTexture,
    ContainerFrame5Item6NormalTexture,
    ContainerFrame5Item5NormalTexture,
    ContainerFrame5Item4NormalTexture,
    ContainerFrame5Item3NormalTexture,
    ContainerFrame5Item2NormalTexture,
    ContainerFrame5Item1NormalTexture,
  }
}
